import { DataType } from "@/components/data-table/types-and-interfaces";
import type { Justify } from "@/components/data-table/types-and-interfaces";

export const columnSchema = [
  {
    key: "id",
    label: "ID",
    dataType: DataType.NUMBER,
    justify: "end" as Justify,
    size: 150,
  },
  {
    key: "name",
    label: "Full Name",
    dataType: DataType.STRING,
    justify: "start" as Justify,
  },
  {
    key: "department",
    label: "Department",
    dataType: DataType.STRING,
    justify: "center" as Justify,
  },
  {
    key: "age",
    label: "Age",
    dataType: DataType.NUMBER,
    justify: "end" as Justify,
  },
  {
    key: "joined",
    label: "Join Date",
    dataType: DataType.DATE,
    justify: "center" as Justify,
  },
  {
    key: "salary",
    label: "Salary (USD)",
    dataType: DataType.CURRENCY,
    justify: "end" as Justify,
  },
  {
    key: "remote",
    label: "Remote",
    dataType: DataType.BOOLEAN,
    justify: "center" as Justify,
  },
  {
    key: "score",
    label: "Performance Score",
    dataType: DataType.PERCENT,
    justify: "end" as Justify,
  },
  {
    key: "projects",
    label: "Projects Completed",
    dataType: DataType.NUMBER,
    justify: "end" as Justify,
  },
  {
    key: "active",
    label: "Active",
    dataType: DataType.BOOLEAN,
    justify: "center" as Justify,
  },
  {
    key: "level",
    label: "Level",
    dataType: DataType.STRING,
    justify: "center" as Justify,
  },
  {
    key: "lastLogin",
    label: "Last Login",
    dataType: DataType.DATETIME,
    justify: "center" as Justify,
  },
] as const;

export const employeeData = [
  {
    id: 1,
    name: "Alice Johnson",
    department: "Engineering",
    age: 29,
    joined: "2020-01-15",
    salary: 95000,
    remote: true,
    score: 0.87,
    projects: 12,
    active: true,
    level: "Senior",
    lastLogin: "2025-07-19T14:23:00Z",
  },
  {
    id: 2,
    name: "Bob Smith",
    department: "Marketing",
    age: 34,
    joined: "2019-08-01",
    salary: 72000,
    remote: false,
    score: 0.75,
    projects: 8,
    active: true,
    level: "Mid",
    lastLogin: "2025-07-20T09:10:00Z",
  },
  {
    id: 3,
    name: "Carol Chen",
    department: "Design",
    age: 26,
    joined: "2021-03-20",
    salary: 68000,
    remote: true,
    score: 0.91,
    projects: 10,
    active: true,
    level: "Junior",
    lastLogin: "2025-07-18T22:40:00Z",
  },
  {
    id: 4,
    name: "Daniel Patel",
    department: "Sales",
    age: 31,
    joined: "2018-06-10",
    salary: 88000,
    remote: false,
    score: 0.65,
    projects: 7,
    active: false,
    level: "Mid",
    lastLogin: "2025-06-30T11:00:00Z",
  },
  {
    id: 5,
    name: "Eva Müller",
    department: "HR",
    age: 38,
    joined: "2017-09-05",
    salary: 71000,
    remote: true,
    score: 0.82,
    projects: 5,
    active: true,
    level: "Senior",
    lastLogin: "2025-07-15T08:30:00Z",
  },
  {
    id: 6,
    name: "Frank Lee",
    department: "Engineering",
    age: 27,
    joined: "2022-12-11",
    salary: 87000,
    remote: false,
    score: 0.93,
    projects: 14,
    active: true,
    level: "Mid",
    lastLogin: "2025-07-20T06:45:00Z",
  },
  {
    id: 7,
    name: "Grace Kim",
    department: "Design",
    age: 24,
    joined: "2023-05-25",
    salary: 64000,
    remote: true,
    score: 0.89,
    projects: 6,
    active: true,
    level: "Junior",
    lastLogin: "2025-07-19T23:00:00Z",
  },
  {
    id: 8,
    name: "Henry Nguyen",
    department: "Sales",
    age: 36,
    joined: "2020-02-17",
    salary: 82000,
    remote: false,
    score: 0.68,
    projects: 11,
    active: false,
    level: "Senior",
    lastLogin: "2025-07-01T14:10:00Z",
  },
  {
    id: 9,
    name: "Isla Thompson",
    department: "Engineering",
    age: 32,
    joined: "2019-04-03",
    salary: 91000,
    remote: true,
    score: 0.84,
    projects: 13,
    active: true,
    level: "Senior",
    lastLogin: "2025-07-19T10:55:00Z",
  },
  {
    id: 10,
    name: "Jack Rivera",
    department: "Marketing",
    age: 30,
    joined: "2021-07-29",
    salary: 75000,
    remote: false,
    score: 0.77,
    projects: 9,
    active: true,
    level: "Mid",
    lastLogin: "2025-07-20T01:05:00Z",
  },
];
